global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: letmecook
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8000"