global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: letmecook
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8000"