route:
  receiver: 'mail'
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  group_by: ['alertname']

receivers:
  - name: 'mail'
    email_configs:
      - to: 'receiver@xxx.de'
        from: 'sender@yyy.de'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'sender@yyy.de'
        auth_identity: 'sender@yyy.de'
        auth_password: "password from sender"
        send_resolved: true