route:
  receiver: 'mail'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  group_by: ['alertname']

receivers:
  - name: 'mail'
    email_configs:
      - to: '<receiver@provider.de>'
        from: '<sender@gmail.de>'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '<sender@gmail.de>'
        auth_identity: '<sender@gmail.de>'
        auth_password: "password from sender"
        send_resolved: true